// 108問のデータ
const QUESTIONS = [
  // Morning Focus：今日の焦点を定める (No.1-15)
  { id: 1, category: "Morning Focus", question: "今日、絶対に達成したい「たった一つの成果」は具体的に何か？" },
  { id: 2, category: "Morning Focus", question: "今日の仕事が終わったとき、どんな気分でいたいか？ そのために何をするか？" },
  { id: 3, category: "Morning Focus", question: "今日、80点の合格ラインを超えるために、一点突破すべき「最重要課題」は何か？" },
  { id: 4, category: "Morning Focus", question: "今日、あえて「やらない」と決めることは何か？" },
  { id: 5, category: "Morning Focus", question: "今日の自分に「テーマ（お題）」を与えるとしたら、どんな言葉にするか？" },
  { id: 6, category: "Morning Focus", question: "今日会う人たちに、どんな価値（GIVE）を提供できるか？" },
  { id: 7, category: "Morning Focus", question: "今日、一つだけ「昨日と違うやり方」を試すとしたら、何を変えるか？" },
  { id: 8, category: "Morning Focus", question: "今日の予定の中で、一番の「楽しみ（ご褒美）」をどう作るか？" },
  { id: 9, category: "Morning Focus", question: "もし今日が人生最後の日なら、今の予定をどう書き換えるか？" },
  { id: 10, category: "Morning Focus", question: "今日の仕事でボトルネックになりそうなことは何か？ どう先手を打つか？" },
  { id: 11, category: "Morning Focus", question: "今日、誰に対し、どんな「感謝」を言葉にして伝えるか？" },
  { id: 12, category: "Morning Focus", question: "今日、一番気が進まないが最もインパクトがあるタスク（カエル）を、いつ片付けるか？" },
  { id: 13, category: "Morning Focus", question: "今日の自分の「機嫌」を良くするために、朝イチで具体的に何をするか？" },
  { id: 14, category: "Morning Focus", question: "今日、決断を先送りにしてしまっていることがあるとしたら、それは何か？" },
  { id: 15, category: "Morning Focus", question: "昨日の反省を活かし、今日具体的に変える「行動」は何か？" },

  // Productivity & AI：AI時代の生産性と成果 (No.16-30)
  { id: 16, category: "Productivity & AI", question: "その作業をAIやツールに「丸投げ」するとしたら、具体的にどの部分か？" },
  { id: 17, category: "Productivity & AI", question: "今やっている仕事が手段の目的化になっていないか確認するため、本来の「目的」を書き出すとどうなるか？" },
  { id: 18, category: "Productivity & AI", question: "この課題について、AIを「壁打ち相手」にして視点を広げるとしたら、何を問いかけるか？" },
  { id: 19, category: "Productivity & AI", question: "AIが出した答えに対し、自分はどんな「人間的な洞察」や「経験」を加えられるか？" },
  { id: 20, category: "Productivity & AI", question: "1時間かかっているその仕事を、15分で終わらせるにはどう手順を変えるか？" },
  { id: 21, category: "Productivity & AI", question: "今の仕事のやり方で、1年前と比べて「進化させている部分」はどこか？" },
  { id: 22, category: "Productivity & AI", question: "集中力を阻害する通知や環境を、今日はどうやってブロックするか？" },
  { id: 23, category: "Productivity & AI", question: "「思考する時間（クリエイティブ）」と「作業する時間（オペレーション）」を分けるために、今日どの時間を確保するか？" },
  { id: 24, category: "Productivity & AI", question: "自分がやらなくても80点の出来になる仕事があるとしたら、誰にどう任せるか？" },
  { id: 25, category: "Productivity & AI", question: "今日の会議を非同期（チャット・録画）で代替し、時間を浮かせるとしたらどれか？" },
  { id: 26, category: "Productivity & AI", question: "完璧主義になりすぎてスピードが落ちている作業を、どうやって「及第点」で終わらせるか？" },
  { id: 27, category: "Productivity & AI", question: "成果物の「質」を落とさず、「労力」を半分にする方法は何か？" },
  { id: 28, category: "Productivity & AI", question: "自分の時給に見合わない「低付加価値な作業」を減らすために、今日何をやめるか？" },
  { id: 29, category: "Productivity & AI", question: "今日触れる新しいテクノロジーやツールを使って、何を試すか？" },
  { id: 30, category: "Productivity & AI", question: "「忙しい」を言い訳にして後回しにしている「重要な思考」は何か？" },

  // Value & Strengths：自分自身の強みと進化 (No.31-45)
  { id: 31, category: "Value & Strengths", question: "自分の最大の強みを、今日のどの場面で、どう発揮するか？" },
  { id: 32, category: "Value & Strengths", question: "最近、周囲から褒められたり感謝されたりしたことから、自分のどんな価値が見えるか？" },
  { id: 33, category: "Value & Strengths", question: "自分が「努力しなくても自然にできてしまうこと（才能）」は具体的に何か？" },
  { id: 34, category: "Value & Strengths", question: "他の人には苦痛でも、自分には楽しいと思える作業は何か？" },
  { id: 35, category: "Value & Strengths", question: "過去の成功体験から、今日再現できる「勝ちパターン」は具体的に何か？" },
  { id: 36, category: "Value & Strengths", question: "自分の市場価値を上げるために、今日できる小さなアウトプットは何か？" },
  { id: 37, category: "Value & Strengths", question: "自信がないと感じている分野は、本当に克服すべき弱点か？（無視していいものではないか？）" },
  { id: 38, category: "Value & Strengths", question: "自分の「弱み」を、愛嬌や他者の協力でカバーするにはどう頼めばいいか？" },
  { id: 39, category: "Value & Strengths", question: "プロフェッショナルとして、絶対に譲れない「美学」を言葉にすると何か？" },
  { id: 40, category: "Value & Strengths", question: "昨日の自分より、今日の自分が1mm成長したと言えるように何をするか？" },
  { id: 41, category: "Value & Strengths", question: "憧れのロールモデルなら、今の自分の状況でどう振る舞うか？" },
  { id: 42, category: "Value & Strengths", question: "自分という商品の「最新の売り（USP）」を一言で宣伝すると？" },
  { id: 43, category: "Value & Strengths", question: "誰の役に立っているとき、自分は最も輝いているか？" },
  { id: 44, category: "Value & Strengths", question: "自分の意見や直感を恐れずに発言するために、どんな準備をするか？" },
  { id: 45, category: "Value & Strengths", question: "今の自分を、100点満点で何点と評価するか？ 足りない点数をどう補うか？" },

  // Emotional Intelligence：感情と人間関係の質 (No.46-60)
  { id: 46, category: "Emotional Intelligence", question: "今日会う相手の「背景」や「今の感情」について、どんな仮説を持てるか？" },
  { id: 47, category: "Emotional Intelligence", question: "相手の思考を深めるために、今日どんな「問いかけ」を投げかけるか？" },
  { id: 48, category: "Emotional Intelligence", question: "相手の言葉の裏にある「感情」や「真意」を掴むために、どこに注目して話を聞くか？" },
  { id: 49, category: "Emotional Intelligence", question: "苦手なあの人の、尊敬できる（見習うべき）点は具体的にどこか？" },
  { id: 50, category: "Emotional Intelligence", question: "最近、感情的になってしまったのはなぜか？（自分の地雷は何だったか？）" },
  { id: 51, category: "Emotional Intelligence", question: "「察してほしい」と甘えず、言葉にして伝えるべきことは何か？" },
  { id: 52, category: "Emotional Intelligence", question: "言いにくいことを、相手を尊重しながら（アサーティブに）伝えるには、どう切り出すか？" },
  { id: 53, category: "Emotional Intelligence", question: "自分の「正しさ」を押し付けず、相手の言い分を聞くためにどう質問するか？" },
  { id: 54, category: "Emotional Intelligence", question: "会話の中で相手の名前を自然に呼ぶために、どのタイミングを意識するか？" },
  { id: 55, category: "Emotional Intelligence", question: "今日、周囲の人のどんな「小さな変化」や「隠れた貢献」を見つけたいか？" },
  { id: 56, category: "Emotional Intelligence", question: "批判的な意見を防御せず「フィードバック」として活かすために、まず何と返答するか？" },
  { id: 57, category: "Emotional Intelligence", question: "相手が「話しやすい」と感じる余白（隙）を作るために、自分の態度をどう変えるか？" },
  { id: 58, category: "Emotional Intelligence", question: "今日、誰かを笑顔にするために、どんな些細な行動をとるか？" },
  { id: 59, category: "Emotional Intelligence", question: "嫉妬や劣等感を感じたとき、それをどう「成長のエネルギー」に変えるか？" },
  { id: 60, category: "Emotional Intelligence", question: "自分が間違っていたとき、言い訳せずに素直に謝るために、どんな言葉を口にするか？" },

  // Resilience：変化への適応とメンタル (No.61-75)
  { id: 61, category: "Resilience", question: "想定外のトラブルが起きたとき、まず「深呼吸」をしてから次の一手をどう打つか？" },
  { id: 62, category: "Resilience", question: "その「失敗」を「データ収集（実験結果）」と捉え直すとしたら、どんな学びが得られるか？" },
  { id: 63, category: "Resilience", question: "今抱えている不安の9割は起こらないとしたら、残りの1割のために何を備えるか？" },
  { id: 64, category: "Resilience", question: "「変えられないこと（他人・過去）」へのエネルギー浪費をやめ、今何に集中し直すべきか？" },
  { id: 65, category: "Resilience", question: "変化を恐れているのは、具体的に「何を失う」と思っているからか？" },
  { id: 66, category: "Resilience", question: "今の状況の邪魔をしている「過去の成功体験（アンラーニングすべきこと）」は何か？" },
  { id: 67, category: "Resilience", question: "今、一番ストレスを感じていることを紙に書き出し、どう対策するか？" },
  { id: 68, category: "Resilience", question: "一人で抱え込まず「助けて」と言うために、まず誰にどう相談するか？" },
  { id: 69, category: "Resilience", question: "この困難な状況をゲームの「イベント」として楽しむなら、どう攻略するか？" },
  { id: 70, category: "Resilience", question: "自分のメンタルが落ち込む「パターン（前兆）」に気づいたら、どうリセットするか？" },
  { id: 71, category: "Resilience", question: "今手放せば、一番身軽になれる「思い込み」は何か？" },
  { id: 72, category: "Resilience", question: "今の苦労は、将来の自伝の「どの章」の、どんなエピソードになるか？" },
  { id: 73, category: "Resilience", question: "完璧な状況を待つのをやめ、「見切り発車」で今日動かせることは何か？" },
  { id: 74, category: "Resilience", question: "他人の評価軸ではなく、自分の「納得感」で判断するために、どの基準を大切にするか？" },
  { id: 75, category: "Resilience", question: "寝る前に「今日はよくやった」と自分を労うために、何を完了させるか？" },

  // Leadership：周囲への影響力 (No.76-90)
  { id: 76, category: "Leadership", question: "今日、チームメンバーのモチベーションスイッチをどう押すか？" },
  { id: 77, category: "Leadership", question: "言葉ではなく、自分の「背中（行動）」で何を語るか？" },
  { id: 78, category: "Leadership", question: "部下や後輩の「隠れた強み」を見つけ、それをどう本人にフィードバックするか？" },
  { id: 79, category: "Leadership", question: "チームの目標を、誰もがワクワクする「物語」としてどう語り直すか？" },
  { id: 80, category: "Leadership", question: "心理的安全性を作るために、自分のどんな「弱み」をあえてさらけ出すか？" },
  { id: 81, category: "Leadership", question: "指示出しを「問いかけ」に変えるとしたら、メンバーにどんな質問を投げるか？" },
  { id: 82, category: "Leadership", question: "誰かの新しいチャレンジを心から応援するために、今日どんな行動をとるか？" },
  { id: 83, category: "Leadership", question: "チーム内の「縁の下の力持ち」に光を当て、どう感謝を伝えるか？" },
  { id: 84, category: "Leadership", question: "自分の機嫌で職場の空気を汚さないために、どう振る舞いを整えるか？" },
  { id: 85, category: "Leadership", question: "「信頼残高」を増やすために、今日どんな誠実な行動をとるか？" },
  { id: 86, category: "Leadership", question: "メンバーが自走するために、自分が「手放すべき権限」は何か？" },
  { id: 87, category: "Leadership", question: "犯人探しではなく「仕組みの欠陥」に目を向け、具体的にどこを改善するか？" },
  { id: 88, category: "Leadership", question: "異なる意見を持つ人を遠ざけず、「多様性」として活かすにはどう接するか？" },
  { id: 89, category: "Leadership", question: "今日、誰のメンター（相談役）として時間を割き、どんな支援をするか？" },
  { id: 90, category: "Leadership", question: "「自分がいなくてもチームが回る状態」を作るために、今日何を仕組み化するか？" },

  // Future Strategy：キャリアと未来への投資 (No.91-100)
  { id: 91, category: "Future Strategy", question: "3年後、どんな景色の中で、誰と笑って働いていたいか？" },
  { id: 92, category: "Future Strategy", question: "今の仕事の延長線上に望む未来がないとしたら、今日から軌道をどう修正するか？" },
  { id: 93, category: "Future Strategy", question: "業界の未来予測やトレンドについて、今週何をインプットし、どう活かすか？" },
  { id: 94, category: "Future Strategy", question: "会社の看板を外したとき、自分に残る資産（スキル・人脈・信用）は具体的に何か？" },
  { id: 95, category: "Future Strategy", question: "AI時代でも陳腐化しない、自分の「希少性」をどこに見出すか？" },
  { id: 96, category: "Future Strategy", question: "未来のために、今投資すべき「リスキリング（学び直し）」は具体的に何か？" },
  { id: 97, category: "Future Strategy", question: "尊敬できる社外のネットワーク（サードプレイス）を広げるために、今日誰に連絡をとるか？" },
  { id: 98, category: "Future Strategy", question: "「5年後になくなる仕事」への時間を減らし、何に時間を再配分するか？" },
  { id: 99, category: "Future Strategy", question: "自分のキャリアに、次にどんな「タグ（掛け算の要素）」を足すか？" },
  { id: 100, category: "Future Strategy", question: "今日1日の行動を、消費ではなく未来への「投資」にするために何を変えるか？" },

  // Essential Life：人生の質と幸福 (No.101-108)
  { id: 101, category: "Essential Life", question: "仕事以外で時間を忘れて没頭できる「情熱の源泉」に、いつ時間を割くか？" },
  { id: 102, category: "Essential Life", question: "家族やパートナーの話を、スマホを置いて「目を見て」聞く時間をいつ作るか？" },
  { id: 103, category: "Essential Life", question: "睡眠、食事、運動。今日、自分の「身体（資本）」をどうメンテナンスするか？" },
  { id: 104, category: "Essential Life", question: "最近、お腹を抱えて笑ったのはいつ、どんな時か？" },
  { id: 105, category: "Essential Life", question: "自然に触れたりデジタルデトックスをして「脳を休める」時間を、どう確保するか？" },
  { id: 106, category: "Essential Life", question: "「忙しい」を言い訳に後回しにしている大切な人と、いつ・どんな時間を過ごすか？" },
  { id: 107, category: "Essential Life", question: "今この瞬間のコーヒーや食事を、五感で味わうためにどう意識を向けるか？" },
  { id: 108, category: "Essential Life", question: "2026年の大晦日、自分にどんな言葉をかけて乾杯したいか？" }
];
